version: '2'
services:
  dev:
    image: node
    volumes:
        - ./react-app/:/usr/app
    command:  npm start
    working_dir: /usr/app
    environment:
        - BROWSER=none
        - HOST=0.0.0.0
    ports:
        - "80:3000"
